# Generated by Django 5.2.3 on 2025-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalemployee",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
