# Generated by Django 5.2.3 on 2025-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_externalemployee_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalemployee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="externalemployee",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="externalemployee",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="externalemployee",
            name="username",
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="bicd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="binm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="deptcd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="deptnm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="eai_dml_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="eai_trans_dt",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="eai_trans_gb",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="empid",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="enfstnm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="enlstnm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="epid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="epmail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="epmobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="epoffice_tel",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="epuserid",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="frcd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="frenm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="frnm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="incumbcd",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="jobgrdcd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="jobgrdnm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalemployee",
            name="pstcd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
